import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header
          name="Hector Camilo Henriquez"
          accountNumber="41611213"
          className=" ESTRUCTURA DE DATOS"
          section="67"
        />
        <main className="flex-1">{children}</main>
        <Footer
          name="Hector Camilo Henriquez"
          email="henriquezhector1@hotmail.com"
          github="/hnkatze"
          linkedin="https://www.linkedin.com/in/hnkatze/"
        />
        <Toaster />
      </body>
    </html>
  );
}
